version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    ports:
      - "8001:8001"
    depends_on:
      - redis
    restart: always
    environment:
      - ACCEPT_EULA=Y
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 5s
      timeout: 5s
      retries: 10

